# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('f', 'future'), ('p', 'past')], default=None, max_length=6)),
                ('Content', models.TextField(default=None)),
                ('StartDatetime', models.DateTimeField()),
                ('EndDatetime', models.DateTimeField()),
                ('Emotion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.TextField(default=None)),
                ('SundayVisitedTimes', models.IntegerField()),
                ('SaturdayVisitedTimes', models.IntegerField()),
                ('MondayVisitedTimes', models.IntegerField()),
                ('TuesdayVisitedTimes', models.IntegerField()),
                ('WednesdayVisitedTimes', models.IntegerField()),
                ('ThursdayVisitedTimes', models.IntegerField()),
                ('FridayVisitedTimes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=30)),
                ('username', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(default=None, max_length=50)),
                ('Age', models.IntegerField()),
                ('Job', models.CharField(default=None, max_length=50)),
                ('user_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skycorn', models.CharField(default=None, max_length=10)),
                ('pm2point5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.CharField(default=None, max_length=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain_intensity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='Region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='Weather',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Weather'),
        ),
    ]
